### ISSUE TITLE
TensorRT MobileNet benchmark results

### ISSUE THREAD

**Issue by chybhao666** [PaddlePaddle/Anakin#101]
I am curious about how you implement depthwise plugin layer in TRT by yourselves? The MobileNet v1, v2 test results do not make sense to me. Why so little latency difference between batchsize=1 and 2?

**Comment by giranntu** [comment]
Any update on this?

**Comment by LittleMaer** [comment]
we will update benchmark with tensorrt4.0 soon

**Comment by giranntu** [comment]
@LittleMaer Interesting... why are we closing the issue?
I have viewed the recent update, didn't have benchmark update with TensorRT4.0.
And that's also not direct related to the topic =>" how you implement depthwise plugin layer in TRT by yourselves? "
