### ISSUE TITLE
ubuntu 16.04 build fail on gcc 4.8.5

### ISSUE THREAD

**Issue by micytw** [PaddlePaddle/Anakin#11]
based on ubuntu [Dockerfile](https://github.com/PaddlePaddle/Anakin/blob/master/docker/gpu/centos7-cuda8-cudnn7-anakin-release/Dockerfile), and changed gcc version to 4.8.5.
error message as follows.

Linking CXX executable ../../output/unit_test/test_saber_buffer_NV
/usr/bin/ld: ../../output/libanakin.so.2.0.1: undefined reference to symbol 'cudnnGetRNNLinLayerBiasParams'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcudnn.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_TargetWrapper.dir/build.make:93: recipe for target '../output/unit_test/test_TargetWrapper' failed
make[2]: *** [../output/unit_test/test_TargetWrapper] Error 1
CMakeFiles/Makefile2:757: recipe for target 'test/CMakeFiles/test_TargetWrapper.dir/all' failed
make[1]: *** [test/CMakeFiles/test_TargetWrapper.dir/all] Error 2

**Comment by pangge** [comment]
Resolved #94
