### ISSUE TITLE
build faild when USE X86 OFF

### ISSUE THREAD

**Issue by cyj1986** [PaddlePaddle/Anakin#12]

**Comment by LittleMaer** [comment]
[https://github.com/PaddlePaddle/Anakin/pull/13](url)

**Comment by LittleMaer** [comment]
## [fix issue： #12](https://github.com/PaddlePaddle/Anakin/pull/13)

**Comment by LittleMaer** [comment]
## [fix issue： #12](https://github.com/PaddlePaddle/Anakin/pull/13)
