### ISSUE TITLE
load saved model failed

### ISSUE THREAD

**Issue by adeagle** [PaddlePaddle/Anakin#161]
WAN| 08:46:02.00618| 6.902s| main_thread| parser.cpp:138]  Parsing in edges of node : relu5_4
 FTL| 08:46:02.00618| 6.902s| main_thread| graph_base.inl:57] Check failed: (this->has_vertex(arc.bottom()) && this->has_vertex(arc.top()))  The arc's top or bottom is not vertex!
 *** Check failed: (this->has_vertex(arc.bottom()) && this->has_vertex(arc.top()))  fatal error: stack trace: ***
 6             0x4a3329 ./anakin_demo() [0x4a3329]
 5       0x7febe6ff2830 __libc_start_main + 240 [??:0]
4             0x4a420b ./anakin_demo() [0x4a420b]
 3       0x7febe8878e96 anakin::graph::Graph<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, (anakin::Precision)0>::load(std::string) + 202 [??:0]
 2       0x7febe877e99a anakin::Status anakin::parser::load<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, (anakin::Precision)0>(anakin::graph::Graph<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, (anakin::Precision)0>*, std::string&) + 69 [??:0]
 1       0x7febe877f4d2 anakin::Status anakin::parser::load<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, (anakin::Precision)0>(anakin::graph::Graph<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, (anakin::Precision)0>*, char const*) + 2656 [??:0]
 0             0x4e5cbd anakin::graph::GraphBase<std::string, std::shared_ptr<anakin::graph::Node<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, (anakin::Precision)0> >, anakin::saber::Tensor<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1, anakin::saber::NCHW>*, anakin::graph::Edge<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1> >::add_in_arc(anakin::graph::Edge<anakin::saber::TargetType<(anakin::saber::TargetTypeEnum)1>, (anakin::saber::DataType)1>&) + 451 [??:?]

**Comment by LittleMaer** [comment]
Would you be able to share us your prototxt file? That would help us investigate what the discrepancy might be.

**Comment by adeagle** [comment]
sorry forgort  graph->Reshape("input_0", {1, 3, 224, 224});
