### ISSUE TITLE
ubuntu build fail 

### ISSUE THREAD

**Issue by throneclay** [PaddlePaddle/Anakin#4]
使用ubuntu 16.04 编译报错，gcc版本5.4。报错信息如下：
`/usr/include/c++/5/bits/stl_function.h:357:20: error: no match for ‘operator==’ (operand types are ‘const anakin::graph::io’ and ‘const anakin::graph::io’)
       { return __x == __y; }`

**Comment by pangge** [comment]
This bug has been fixed
