### ISSUE TITLE
drop error

### ISSUE THREAD

**Issue by OMG59E** [PaddlePaddle/Anakin#520]
layer {
    bottom: "cnn/conv7"
    top: "cnn/conv7"
    name: "cnn/bn_conv7"
    type: "BatchNorm"
}
layer {
    bottom: "cnn/conv7"
    top: "cnn/conv7"
    name: "cnn/scale_conv7"
    type: "Scale"
    scale_param {
        bias_term: true
    }
}
layer {
  name: "cnn/relu7"
  type: "ReLU"
  bottom: "cnn/conv7"
  top: "cnn/conv7"
}

layer {
  name: "cnn/drop"
  type: "Dropout"
  bottom: "cnn/conv7"
  top: "cnn/drop"
  dropout_param {
    dropout_ratio: 0.7
  }
}

layer {
    name: "cnn/permute0"
    type: "Permute"
    bottom: "cnn/drop"
    top: "cnn/permute0"
    permute_param {
        order: 0
        order: 2
        order: 3
        order: 1
    }
}

FTL | 2019-05-26 18:54:21.904228 | parser_caffe.py:326 _InsertSplits() ]  Unknown bottom (blob: cnn/drop) in (layer: 'cnn/permute0')

**Comment by throneclay** [comment]
drop out is not used in inference, you can just delete this layer
