### ISSUE TITLE
抄袭了Arm的ComputeLibrary是否应该给出说明？

### ISSUE THREAD

**Issue by izp001** [PaddlePaddle/Anakin#527]
既然开源了，就要遵守游戏规则

**Comment by yiicy** [comment]
> 既然开源了，就要遵守游戏规则

请问指的是哪部分文件

**Comment by throneclay** [comment]
没人回复这个就关了，如果有问题可以随时跟我们联系

**Comment by izp001** [comment]
你们自己不知道吗？连注释都一样，有朋友问我了，我就给你指出来，你们最好修改以后再说没抄
sgemm_arm.cpp
/**
 * Sgemm Kernel implementation for arm-v7a
 * Assume that "Apanel" points to a chunk of A blocks (each size 6xK) in read-order.
 * Assume that "Bpanel" points to a chunk of B blocks (each size 8xK) in read-order.
 * Assume that "Cpanel" points to a chunk of C output blocks (each size 8x6),
 * the chunks being arranged in a row major fashion.
 * Note that the intent of this is that either ablocks or bblocks will be 1
 * - this construction allows the output loop to proceed in either order.
 */
而ComputeLibrary的generic.cpp
ComputeLibrary/src/core/NEON/kernels/arm_gemm/kernels/a32_sgemm_8x6/generic.cpp
// Kernel implementation.
//
// Assume that "Apanel" points to a chunk of A blocks (each size 6xK) in read-order.
// Assume that "Bpanel" points to a chunk of B blocks (each size 8xK) in read-order.
// Assume that "Cpanel" points to a chunk of C output blocks (each size
// 8x6), the chunks being arranged in a row major fashion.
//
// Note that the intent of this is that either ablocks or bblocks will be 1
// - this construction allows the output loop to proceed in either order.

**Comment by izp001** [comment]
你们开源是值得鼓励的，但是开源参考了就要说明，不然丢中国人的脸

**Comment by yiicy** [comment]
> 你们开源是值得鼓励的，但是开源参考了就要说明，不然丢中国人的脸

感谢指出问题，我们最开始的GEMM借鉴了compute library，现在sgemm.cpp里的接口已经弃用了，统一使用sgemm_prepacked.cpp里的接口，实现上也做了相应的变化，sgemm_prepacked.cpp的xblock将按照l2 cache大小划分

**Comment by daquexian** [comment]
> > 你们开源是值得鼓励的，但是开源参考了就要说明，不然丢中国人的脸
> 
> 感谢指出问题，我们最开始的GEMM借鉴了compute library，现在sgemm.cpp里的接口已经弃用了，统一使用sgemm_prepacked.cpp里的接口，实现上也做了相应的变化，sgemm_prepacked.cpp的xblock将按照l2 cache大小划分

这和弃不弃用无关。您能不能遵守[开源协议](https://github.com/ARM-software/ComputeLibrary/blob/master/LICENSE)、尊重原作者的权利呢？

**Comment by daquexian** [comment]
@throneclay 

> 没人回复这个就关了，如果有问题可以随时跟我们联系

我联系了，你们的回复呢？

**Comment by xyoungli** [comment]
> 既然开源了，就要遵守游戏规则
您好，该问题与#531issue合并，如有疑问可以随时联系
#531
