### ISSUE TITLE
Support for different input shapes between frames

### ISSUE THREAD

**Issue by hxbloom** [PaddlePaddle/Anakin#98]
Hi, I have a new question,

Does Anakin support “variadic” input shapes?   For example, in frame 1, I have one standard 224*224 image as input. But in frame 2, I have another image of any arbitrary size like 456*789.    I would like to know if Anakin could support. 

Thank you~ ~

**Comment by LittleMaer** [comment]
Anakin support variable length input size. If you set the maximum value, anakin can still maintain very high performance.

**Comment by hxbloom** [comment]
Thanks!
